### ISSUE TITLE
Restoring Default Firmware without JLink

### ISSUE THREAD

**Issue by Eulerianial** [ErichStyger/Hexiwear_v2#1]
Is it possible to restore default firmware of Hexiwear without using JLink?

**Comment by ErichStyger** [comment]
You don't need a J-Link, but some type of JTAG/SWD programmer. This could be a SEGGER J-Link, a P&E Multilink, a LPC-Link2 or anything else which you can use to program the device with the SWD protocol. You might use a Freedom or Tower board too if you load the right firmware.

**Comment by Eulerianial** [comment]
Erich, is it possible with just Docking station because I probably won't get funds to buy the JTAG devices.

**Comment by ErichStyger** [comment]
No, you cannot do it with just the docking station. You need a JTAG device. And you need such a JTAG device anyway for any serious work. The J-Link EDU is only about Euro 50 (https://www.segger.com/products/debug-probes/j-link/models/j-link-edu/), and the LPC-Link2 even costs less than Euro 20: (search for 'LPC-Link2' e.g. on Mouser.com (http://www.nxp.com/products/microcontrollers-and-processors/arm-processors/lpc-cortex-m-mcus/lpc1100-cortex-m0-plus-m0/lpc-link2:OM13054).

**Comment by Eulerianial** [comment]
I am bit confused. Here on this link the instructions need only Docking station: https://developer.mbed.org/questions/69735/HexiWear-Docking-Station-Firmware/

Am I missing something?

**Comment by ErichStyger** [comment]
If the bootloader has been erased/damaged, you need a JTAG programmer to restore it. The K20 (OpenSDA) device does *not* have a ROM bootloader, so you will need a JTAG device in that case.
I hope this helps?

**Comment by Eulerianial** [comment]
I see. Is there a way to check if the bootlaoder is damaged/erased. When I plug in the Docking station with Hexiwear. I see following files:
DAPLIJK (f:/)
 - Debug
-  MBED

Then everytime I try to load a BIN file, it runs but throws a file:
FAIL.txt

Does it mean the bootloader is damaged?

**Comment by ErichStyger** [comment]
if it comes up as DAPLIJK, then it seems the bootloader is working. But if it fails, it means your BIN file is wrong/corrupted. In any case, disable your virus scanner and copy the file from the DOS Prompt.

**Comment by Eulerianial** [comment]
Erich I have following BIN files which I am trying to flash:
**For MK64**: (With all the switches on except KW40)
https://github.com/MikroElektronika/HEXIWEAR/blob/master/SW/MK64%20KDS/HEXIWEAR_MK64/binary/HEXIWEAR_MK64_v103.bin

**For MK40**: (With all the switches on except MK64)
https://github.com/MikroElektronika/HEXIWEAR/blob/master/SW/KW40%20IAR/HEXIWEAR_bluetooth/binary/HEXIWEAR_KW40_v100.bin

Are these steps and BIN files okay?

**Comment by ErichStyger** [comment]
Yes, these BIN files shall be ok.
