### ISSUE TITLE
getting error : invalid literal for int() with base 16

### ISSUE THREAD

**Issue by anandpanchal** [ErichStyger/Hexiwear_v2#2]
Hi All,

getting error : invalid literal for int() with base 16.
please help me.

thanks

**Comment by ErichStyger** [comment]
I would need more details, but it looks like you are not using a correct number for the interger.

**Comment by anandpanchal** [comment]
![whatsapp image 2017-12-13 at 3 08 32 pm](https://user-images.githubusercontent.com/34059153/33934074-c230c4ca-e01d-11e7-9280-da19bab391b1.jpeg)

**Comment by anandpanchal** [comment]
![whatsapp image 2017-12-13 at 2 54 47 pm](https://user-images.githubusercontent.com/34059153/33934140-f693b0ec-e01d-11e7-935b-c3ead397c5a8.jpeg)

**Comment by anandpanchal** [comment]
please help me

**Comment by ErichStyger** [comment]
which file is this from this GitHub repository?

**Comment by anandpanchal** [comment]
https://github.com/ErichStyger/Hexiwear_v2/blob/master/KDS/Hexiwear_PEx_Dockingstation/Raspy/GetData.py

**Comment by ErichStyger** [comment]
There is no such print statement on line 70 of that file.

**Comment by anandpanchal** [comment]
im executing code for battery only. please check lines from 77 to 86. im getting this error on 83 and 85. output data is 02 03 00 00 2a( UTF-8 format), i need to convert it into integer.

**Comment by ErichStyger** [comment]
I have rechecked this, but I don't have that error?
